before_install:
  - chmod +x install-server.sh
  - chmod +x install-client.sh
install: 
  - ./install-server.sh
  - ./install-client.sh
before_script:
  - chmod +x build-server.sh
  - chmod +x test-server.sh
  - chmod +x build-client.sh
script: 
  - ./build-server.sh
  - ./test-server.sh
  - ./build-client.sh
